name: tribelog

services:
  db:
    image: postgres:16-alpine
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - backend

  api:
    build: ./Tribelog
    ports:
      - 8080:8080
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
