name: tribelog_dev_db

services:
  db:
    image: postgres:16-alpine
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=dev
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  db_data:
